### 유저 회원가입 (회원)
POST http://localhost:8080/users/sign-up
Content-Type: application/json

{
  "id": 0,
  "userId": "jinan",
  "password": "123",
  "nickName": "test",
  "createTime": "2024-03-21T19:55:29.500",
  "isWithdraw": "false",
  "isAdmin": "false",
  "status": "DEFAULT"
}

### 유저 회원가입 (관리자)
POST http://localhost:8080/users/sign-up
Content-Type: application/json

{
  "id": 1,
  "userId": "admin",
  "password": "123",
  "nickName": "admin",
  "createTime": "2024-03-21T19:55:29.500",
  "isWithdraw": "false",
  "isAdmin": "true",
  "status": "ADMIN"
}

### 유저 로그인 (회원)
POST http://localhost:8080/users/sign-in
Content-Type: application/json

{
  "userId": "jinan",
  "password": "123"
}

### 유저 로그인 (관리자)
POST http://localhost:8080/users/sign-in
Content-Type: application/json

{
  "userId": "admin",
  "password": "123"
}

### 유저 로그인 후 정보 조회 (로그인 후에 호출해야함)
GET http://localhost:8080/users/my-info


### 유저 비밀번호 변경
PATCH http://localhost:8080/users/password
Content-Type: application/json

{
  "beforePassword": "123",
  "afterPassword": "1234"
}

### 유저 로그아웃
PUT http://localhost:8080/users/logout
Content-Type: application/x-www-form-urlencoded

### 유저 삭제
DELETE http://localhost:8080/users
Content-Type: application/json

{
  "id": "jinan",
  "password": "1234"
}

### 카테고리 생성 (관리자만 가능)
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "중고거래1"
}

### 카테고리 수정 (관리자만 가능)
PATCH http://localhost:8080/categories/1
Content-Type: application/json

{
  "id": 1,
  "name": "중고거래 수정"
}

### 카테고리 삭제 (관리자만 가능)
DELETE http://localhost:8080/categories/1

### 게시글 생성
POST http://localhost:8080/posts/register
Content-Type: application/json

{
  "id": 0,
  "name": "test",
  "isAdmin": 0,
  "contents": "test1",
  "createTime": "2024-03-23T19:55:29.500",
  "views": 0,
  "categoryId": 1,
  "userId": 0,
  "fileId": 1,
  "updateTime": "2024-03-23T19:55:29.500"
}

### 게시글 조회
GET http://localhost:8080/posts/my-posts

### 게시글 수정
PATCH http://localhost:8080/posts/3
Content-Type: application/json

{
  "name": "테스트 수정",
  "contents": "콘텐츠 수정",
  "categoryId": 1,
  "fileId": 1,
  "updateTime": "2024-03-23T19:55:29.500"
}

### 게시글 삭제
DELETE http://localhost:8080/posts/3