### 게시글 검색
POST http://localhost:8080/search
Content-Type: application/json

{
  "name": "te",
  "contents": "test",
  "categoryId": 1,
  "sortStatus": "CATEGORIES"
}

### 게시글 검색 (태그)
GET http://localhost:8080/search?tagName=자유 게시판2